/**
 * CSS Variables Exporter — generates a :root CSS custom properties block.
 */

import type { DesignSystem, Exporter, ExportFile } from '../types/index.js';

export class CssVarsExporter implements Exporter {
  format = 'css-vars';
  extension = '.css';

  private selector: string;
  private prefix: string;

  constructor(options?: { selector?: string; prefix?: string }) {
    this.selector = options?.selector ?? ':root';
    this.prefix = options?.prefix ?? '--';
  }

  /**
   * Generate a CSS file with custom properties.
   */
  export(ds: DesignSystem): ExportFile {
    const lines: string[] = [
      `/* Generated by stylepeek — https://github.com/stylepeek/stylepeek */`,
      `/* Source: ${ds.meta.url} — ${ds.meta.crawledAt.split('T')[0]} */`,
      '',
      `${this.selector} {`,
    ];

    // Colors
    if (ds.colors.palette.length > 0) {
      lines.push('  /* Colors */');

      // Semantic colors first
      const semantic = ds.colors.semantic;
      if (semantic.primary) lines.push(`  ${this.prefix}color-primary: ${semantic.primary.value.hex};`);
      if (semantic.secondary) lines.push(`  ${this.prefix}color-secondary: ${semantic.secondary.value.hex};`);
      if (semantic.accent) lines.push(`  ${this.prefix}color-accent: ${semantic.accent.value.hex};`);
      if (semantic.background) lines.push(`  ${this.prefix}color-background: ${semantic.background.value.hex};`);
      if (semantic.foreground) lines.push(`  ${this.prefix}color-foreground: ${semantic.foreground.value.hex};`);
      if (semantic.muted) lines.push(`  ${this.prefix}color-muted: ${semantic.muted.value.hex};`);
      if (semantic.danger) lines.push(`  ${this.prefix}color-danger: ${semantic.danger.value.hex};`);
      if (semantic.warning) lines.push(`  ${this.prefix}color-warning: ${semantic.warning.value.hex};`);
      if (semantic.success) lines.push(`  ${this.prefix}color-success: ${semantic.success.value.hex};`);
      if (semantic.info) lines.push(`  ${this.prefix}color-info: ${semantic.info.value.hex};`);

      lines.push('');

      // All palette colors
      for (const group of ds.colors.groups) {
        lines.push(`  /* ${group.name} */`);
        for (const color of group.colors) {
          lines.push(`  ${this.prefix}color-${color.name}: ${color.value.hex};`);
        }
      }
      lines.push('');
    }

    // Typography
    if (ds.typography.fontFamilies.length > 0) {
      lines.push('  /* Typography */');
      for (const ff of ds.typography.fontFamilies) {
        lines.push(`  ${this.prefix}font-${ff.name}: ${ff.raw};`);
      }
      lines.push('');
    }

    if (ds.typography.fontSizes.length > 0) {
      lines.push('  /* Font Sizes */');
      for (const fs of ds.typography.fontSizes) {
        lines.push(`  ${this.prefix}${fs.name}: ${fs.value};`);
      }
      lines.push('');
    }

    if (ds.typography.lineHeights.length > 0) {
      lines.push('  /* Line Heights */');
      for (const lh of ds.typography.lineHeights) {
        lines.push(`  ${this.prefix}${lh.name}: ${lh.value};`);
      }
      lines.push('');
    }

    // Spacing
    if (ds.spacing.length > 0) {
      lines.push('  /* Spacing */');
      for (const s of ds.spacing) {
        lines.push(`  ${this.prefix}${s.name}: ${s.value};`);
      }
      lines.push('');
    }

    // Border Radius
    if (ds.borderRadius.length > 0) {
      lines.push('  /* Border Radius */');
      for (const r of ds.borderRadius) {
        lines.push(`  ${this.prefix}${r.name}: ${r.value};`);
      }
      lines.push('');
    }

    // Shadows
    if (ds.shadows.length > 0) {
      lines.push('  /* Shadows */');
      for (const s of ds.shadows) {
        lines.push(`  ${this.prefix}shadow-${s.name}: ${s.raw};`);
      }
      lines.push('');
    }

    lines.push('}');
    lines.push('');

    return {
      filename: 'variables.css',
      content: lines.join('\n'),
      mimeType: 'text/css',
    };
  }
}
