/**
 * Tailwind Config Exporter — generates a tailwind.config.js
 * from an extracted DesignSystem.
 */

import type { DesignSystem, Exporter, ExportFile } from '../types/index.js';

export class TailwindExporter implements Exporter {
  format = 'tailwind';
  extension = '.js';

  /**
   * Generate a Tailwind CSS configuration file.
   */
  export(ds: DesignSystem): ExportFile {
    const theme = this.buildTheme(ds);
    const content = `/** @type {import('tailwindcss').Config} */
// Generated by stylepeek — ${ds.meta.url}
// Crawled: ${ds.meta.crawledAt}
module.exports = {
  theme: {
    extend: ${this.serializeObject(theme, 3)},
  },
};
`;

    return {
      filename: 'tailwind.config.js',
      content,
      mimeType: 'application/javascript',
    };
  }

  private buildTheme(ds: DesignSystem): Record<string, unknown> {
    const theme: Record<string, unknown> = {};

    // Colors
    if (ds.colors.palette.length > 0) {
      const colors: Record<string, unknown> = {};

      // Add semantic colors
      if (ds.colors.semantic.primary) {
        colors['primary'] = ds.colors.semantic.primary.value.hex;
      }
      if (ds.colors.semantic.secondary) {
        colors['secondary'] = ds.colors.semantic.secondary.value.hex;
      }
      if (ds.colors.semantic.accent) {
        colors['accent'] = ds.colors.semantic.accent.value.hex;
      }
      if (ds.colors.semantic.danger) {
        colors['danger'] = ds.colors.semantic.danger.value.hex;
      }
      if (ds.colors.semantic.warning) {
        colors['warning'] = ds.colors.semantic.warning.value.hex;
      }
      if (ds.colors.semantic.success) {
        colors['success'] = ds.colors.semantic.success.value.hex;
      }
      if (ds.colors.semantic.info) {
        colors['info'] = ds.colors.semantic.info.value.hex;
      }

      // Add grouped colors as scales
      for (const group of ds.colors.groups) {
        if (group.colors.length === 1) {
          colors[group.name] = group.colors[0]!.value.hex;
        } else {
          const scale: Record<string, string> = {};
          group.colors.forEach((c, i) => {
            const step = Math.round((i / (group.colors.length - 1)) * 900) || 50;
            scale[String(step)] = c.value.hex;
          });
          // Set DEFAULT to the middle color
          const mid = Math.floor(group.colors.length / 2);
          scale['DEFAULT'] = group.colors[mid]!.value.hex;
          colors[group.name] = scale;
        }
      }

      if (Object.keys(colors).length > 0) {
        theme['colors'] = colors;
      }
    }

    // Font families
    if (ds.typography.fontFamilies.length > 0) {
      const fontFamily: Record<string, string[]> = {};
      for (const ff of ds.typography.fontFamilies) {
        fontFamily[ff.name] = ff.stack;
      }
      theme['fontFamily'] = fontFamily;
    }

    // Font sizes
    if (ds.typography.fontSizes.length > 0) {
      const fontSize: Record<string, string> = {};
      for (const fs of ds.typography.fontSizes) {
        fontSize[fs.name.replace('text-', '')] = fs.value;
      }
      theme['fontSize'] = fontSize;
    }

    // Spacing
    if (ds.spacing.length > 0) {
      const spacing: Record<string, string> = {};
      for (const s of ds.spacing) {
        spacing[s.name.replace('space-', '')] = s.value;
      }
      theme['spacing'] = spacing;
    }

    // Border radius
    if (ds.borderRadius.length > 0) {
      const borderRadius: Record<string, string> = {};
      for (const r of ds.borderRadius) {
        borderRadius[r.name.replace('radius-', '')] = r.value;
      }
      theme['borderRadius'] = borderRadius;
    }

    // Shadows
    if (ds.shadows.length > 0) {
      const boxShadow: Record<string, string> = {};
      for (const s of ds.shadows) {
        boxShadow[s.name] = s.raw;
      }
      theme['boxShadow'] = boxShadow;
    }

    // Breakpoints
    if (ds.breakpoints.length > 0) {
      const screens: Record<string, string> = {};
      for (const bp of ds.breakpoints.filter((b) => b.type === 'min-width')) {
        screens[bp.name] = bp.value;
      }
      if (Object.keys(screens).length > 0) {
        theme['screens'] = screens;
      }
    }

    return theme;
  }

  private serializeObject(obj: unknown, indent: number): string {
    if (obj === null || obj === undefined) return 'undefined';
    if (typeof obj === 'string') return `'${obj}'`;
    if (typeof obj === 'number' || typeof obj === 'boolean') return String(obj);

    if (Array.isArray(obj)) {
      if (obj.length === 0) return '[]';
      const items = obj.map((item) => this.serializeObject(item, indent + 2));
      const pad = ' '.repeat(indent);
      return `[\n${items.map((i) => `${pad}  ${i}`).join(',\n')}\n${pad}]`;
    }

    if (typeof obj === 'object') {
      const entries = Object.entries(obj as Record<string, unknown>);
      if (entries.length === 0) return '{}';

      const pad = ' '.repeat(indent);
      const lines = entries.map(([key, value]) => {
        const safeKey = /^[a-zA-Z_$][\w$]*$/.test(key) ? key : `'${key}'`;
        return `${pad}  ${safeKey}: ${this.serializeObject(value, indent + 2)}`;
      });

      return `{\n${lines.join(',\n')}\n${pad}}`;
    }

    return String(obj);
  }
}
